### ISSUE TITLE
Add syntax completion

### ISSUE THREAD

**Issue by schnatterer** [cloudogu/helm-sudo#1]
Syntax completion would be very helpful.

How can we bring `helm sudo` to basically provide helm's syntax completion?

Could this be possible using [dynamic completion](https://helm.sh/docs/topics/plugins/#dynamic-completion)?

**Comment by marckhouzam** [comment]
To enable shell completion you can add a `plugin.complete` executable file in your plugin directory with the following content:
```
#!/usr/bin/env bash

$HELM_BIN __complete "$@"
```
It basically asks helm to provide the completion choices.

I hope this helps.

**Comment by marckhouzam** [comment]
Oh, I should mention that you'll need the soon-to-be-released helm 3.8 for this completion to also work for flags.

**Comment by schnatterer** [comment]
Cool, this sounds exactly like what I was looking for back then.

I just tried this with helm 3.8.0-rc2 and it just works! Thanks so much, @marckhouzam!
